# Generated by Django 5.0.6 on 2024-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework4', '0004_alter_order_order_date_alter_product_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
